### ISSUE TITLE
JPA Auditing 오류

### ISSUE THREAD

**Issue by JiseokCheon** [shoestrade/shoestrade#19]
<img width="450" alt="스크린샷 2022-04-21 오후 9 09 57" src="https://user-images.githubusercontent.com/81504973/164455127-6538960b-4544-465f-9e9c-6a77d25ee85a.png">
<img width="455" alt="스크린샷 2022-04-21 오후 9 10 10" src="https://user-images.githubusercontent.com/81504973/164455164-5cc334b1-9834-42a7-b66f-5ad56d7e6d75.png">

trade는 적용되는데 product_image는 적용안됨

**Comment by JiseokCheon** [comment]
jpa를 사용하지 않고 JdbcTemplete을 사용한 도메인들이 적용되지 않아 따로 작성해야 할 것 같다.

**Comment by 0takkk** [comment]
<pre>
<code>
Timestamp now = Timestamp.valueOf(LocalDateTime.now());

private int batchInsertInterest(int batchSize, int batchCount, List<InterestProduct> subInterests, Timestamp now){
        jdbcTemplate.batchUpdate("insert into interest_product (`member_id`, `product_size_id`, `created_date`, `last_modified_date`) values (?, ?, ?, ?)"
                , new BatchPreparedStatementSetter() {
                    @Override
                    public void setValues(PreparedStatement ps, int i) throws SQLException {
                        ps.setLong(1, subInterests.get(i).getMember().getId());
                        ps.setLong(2, subInterests.get(i).getProductSize().getId());
                        ps.setTimestamp(3, now);
                        ps.setTimestamp(4, now);
                    }

                    @Override
                    public int getBatchSize() {
                        return subInterests.size();
                    }
                });
        subInterests.clear();
        batchCount++;
        return batchCount;
    }
</code>
</pre>

JdbcTemplete에서 따로 작성하여 추가하여 해결함.
