### ISSUE TITLE
auto_increment 테이블 bulk insert 적용안됨

### ISSUE THREAD

**Issue by JiseokCheon** [shoestrade/shoestrade#3]
List<ProductSize> list = new ArrayList<>();

        for (int i = 0; i <= 80; i += 5) {
            list.add(ProductSize.builder()
                    .size(220 + i)
                    .product(saveProduct)
                    .build());
        }

        productSizeRepository.saveAll(list);

테이블에서 pk인 id가 auto_increment로 설정되어 있어서 bulk insert(한 트랙잭션으로 insert) 안되고 각 트랜잭션으로 실행됨

하지만 id값이 trade를 위해 필요함, 없으면 product_id와 size로 함께 검색해서 찾아야 됨

**Comment by jscheon** [comment]
하지만 id값 거래를 위해 필요함, 없으면 product_id와 size로 함께 검색해서 찾아야 됨

**Comment by JiseokCheon** [comment]
product_size, product_image를 key mapping 전략 sequence -> identity로 수정 후, spring jdbc 이용해서 bulk insert

문제 : bulk insert 를 위해 flush() 해서 product를 insert 함
-> product 테이블을 sequence 전략으로 하면 sequence 테이블에 쿼리 발생, 하지만 바로   insert 해줘서 의미가 없음

**Comment by JiseokCheon** [comment]
mysql 을 사용하기 때문에 키 생성 전략을 sequence로 해줄 필요성을 느끼지 못해 indentity로 설정해서 mysql의 auto_increment를 사용하기로 함
